<?xml version="1.0"?>
<package format="3">
  <name>ur5e_ros2_control</name>
  <version>0.1.0</version>
  <description>UR5e ROS2 controller validation framework.</description>
  <maintainer email="sooyong@example.com">Sooyong Kim</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ament_index_cpp</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
