import numpy as np

from kinematics.jacobian import geometric_jacobian


# ---------------------------------------------------------------------
# Configuration definitions
# ---------------------------------------------------------------------

q_safe_deg = np.array([
    0.0, -90.0, 90.0, -90.0, -90.0, 0.0
])

q_singular_deg = np.zeros(6)

q_safe = np.deg2rad(q_safe_deg)
q_singular = np.deg2rad(q_singular_deg)


# Damped least-squares damping factor
damping = 0.05


# ---------------------------------------------------------------------
# Table header
# ---------------------------------------------------------------------

print(
    f"{'s':>6} "
    f"{'sigma_min':>12} "
    f"{'||qdot_pinv||':>16} "
    f"{'||qdot_dls||':>16} "
    f"{'err_pinv':>12} "
    f"{'err_dls':>12}"
)

print("-" * 84)


# ---------------------------------------------------------------------
# Sweep from the nominal working pose toward the singular configuration
# ---------------------------------------------------------------------

for s in np.linspace(0.0, 0.99, 21):

    # Linear interpolation in joint space
    q = (
        (1.0 - s) * q_safe
        + s * q_singular
    )

    # Geometric Jacobian
    J = geometric_jacobian(q)

    # Singular value decomposition
    U, singular_values, Vt = np.linalg.svd(J)

    sigma_min = singular_values[-1]

    # Command exactly along the weakest instantaneous
    # task-space direction at the current configuration.
    task_command = U[:, -1]


    # -----------------------------------------------------------------
    # Moore-Penrose pseudoinverse
    # -----------------------------------------------------------------

    qdot_pinv = (
        np.linalg.pinv(J)
        @ task_command
    )


    # -----------------------------------------------------------------
    # Damped least-squares inverse
    #
    # qdot = J^T (J J^T + lambda^2 I)^(-1) v
    # -----------------------------------------------------------------

    JJt = J @ J.T

    qdot_dls = (
        J.T
        @ np.linalg.solve(
            JJt + damping**2 * np.eye(6),
            task_command
        )
    )


    # -----------------------------------------------------------------
    # Task-space tracking errors
    #
    # Compare the requested task-space command with the velocity
    # actually generated by each inverse method.
    # -----------------------------------------------------------------

    pinv_task_error = np.linalg.norm(
        J @ qdot_pinv - task_command
    )

    dls_task_error = np.linalg.norm(
        J @ qdot_dls - task_command
    )


    # -----------------------------------------------------------------
    # Results
    # -----------------------------------------------------------------

    print(
        f"{s:6.2f} "
        f"{sigma_min:12.4e} "
        f"{np.linalg.norm(qdot_pinv):16.6f} "
        f"{np.linalg.norm(qdot_dls):16.6f} "
        f"{pinv_task_error:12.6f} "
        f"{dls_task_error:12.6f}"
    )